steps:
  docker-build:
    image: docker:24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Building Docker image..."
      - docker build -t woodpecker-demo .

    when:
      branch: main
      path:
        include:
          - src/**
          - dockerfile
          - requirements.txt
        exclude:
          - README.md
          - .woodpecker.yml 
