# .woodpecker.yml
# This file is required but can be minimal
# Workflows from .woodpecker/ folder will be picked automatically

clone:
  git:
    image: woodpeckerci/plugin-git

# Optional global settings
pipeline:
  skip_clone: false
